
logging:
  level:
    org:
      springframework: debug

spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:Users_DB}
    username: ${RDS_USERNAME:sign-up-user}
    password: ${RDS_PASSWORD:284veneto}

  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  signing:
    key:
      secret: mySecret
  get:
    token:
      uri: /authenticate
  refresh:
    token:
      uri: /refresh
  http:
    request:
      header: Authorization
  token:
    expiration:
      in:
        seconds: 604800

