
logging:
  level:
    org:
      springframework: debug

spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:billshare}
    username: ${RDS_USERNAME:admin}
    password: ${RDS_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

#spring.jpa.
#  output:
#    ansi:
#      enabled: ALWAYS

jwt:
  signing:
    key:
      secret: mySecret
  get:
    token:
      uri: /authenticate
  refresh:
    token:
      uri: /refresh
  http:
    request:
      header: Authorization
  token:
    expiration:
      in:
        seconds: 604800
server:
  port: 8080
  address: 192.168.86.74


path:
  avatar: /Users/yuning/Documents/GitHub/BillShare/BillShare/src/main/resources/static/image/avatar
  receipt: /Users/yuning/Documents/GitHub/BillShare/BillShare/src/main/resources/static/image/receipt





